import { Provider, connect } from "preact-redux";
import { createStore } from "redux";
import { render, h } from "preact";
import Page01, { mapStateToProps } from "./Page01";

require("preact/devtools");

const container = document.querySelector("#app");
const preloadedState = window.__PRELOADED_STATE__;

// This is at the application level ? not sure...
const rootReducer = (state, action) => {
  switch (action.type) {
    default:
      return state;
  }
};

const store = createStore(
  rootReducer,
  preloadedState,
  window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
);


// this can be autogenerated
const PageConnect = connect(mapStateToProps)(Page01);

// pass store from prerender
render(
  <Provider store={store}>
    <PageConnect />
  </Provider>,
  document.body,
  container
);
